# Logging: SLF4J (via Lombok)
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.de.caritas.cob.uploadservice.scheduler=DEBUG
# Keycloak
spring.datasource.url=jdbc:mariadb://localhost:3306/uploadservice
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.liquibase.change-log=classpath:db/changelog/uploadservice-local-master.xml
spring.liquibase.user=liquibase
spring.liquibase.password=liquibase
spring.liquibase.default-schema=uploadservice

keycloak.auth-server-url=http://onlineberatung.local/auth
keycloak.realm=online-beratung
keycloak.bearer-only=true
keycloak.resource=upload-service
keycloak.principal-attribute=preferred_username
keycloak.cors=false
keycloakService.techuser.id=658c7779-bb6d-42e2-bec9-3f2010b76ea1
keycloakService.admin.username=realmadmin
keycloakService.admin.password=
keycloakService.admin.clientId=admin-cli
# Rocket.Chat
rocket.chat.api.url=http://localhost:3000/api/v1
rocket.systemuser.username=system1
rocket.systemuser.password=
rocket.credentialscheduler.cron=0 0/5 * * * ?